- name: robertdebock.update_package_cache
  version: 1.1.14
- name: robertdebock.core_dependencies
  version: 1.5.0
- name: robertdebock.epel
  version: 2.5.2
- name: geerlingguy.pip
  version: 2.0.0
- name: robertdebock.bootstrap
  version: 4.3.2
- name: robertdebock.update
  version: 2.3.5
- name: robertdebock.users
  version: 4.4.0
- name: robertdebock.firewall
  version: 3.2.8
- name: robertdebock.hostname
  version: 2.0.7
- name: geerlingguy.docker
  version: 2.9.0
- name: igor_mukhin.bash_aliases  
  version: v1.1.0
- name: robertdebock.git
  version: 3.3.7