- include_role:
    name: igor_mukhin.bash_aliases
  vars:
    bash_aliases:
      - { alias: 'setup_tmux',      command: 'tmux new-session -d -s "evilginx"' }
      - { alias: 'start_evilginx2', command: 'docker run -it -p 80:80 -p 443:443 -v /root/.evilginx:/root/.evilginx -v /opt/evilginx2/phishlets/:/app/phishlets evilginx2' }

- include_role:
    name: robertdebock.git
  vars:
    git_username: root
    git_groupname: root 
    git_repository_destination: /opt
    git_repositories:
      - repo: https://github.com/kgretzky/evilginx2
        dest: evilginx2
        version: 2.4.0

- name: Build docker image for evilginx2 from 2.4.0 tag
  docker_image:
    name: evilginx2
    build:
      pull: no
      path: /opt/evilginx2
    source: build

- name: Ensure tmux is installed
  ansible.builtin.package:
    name: tmux
    state: present

- name: Run evilginx2 container in tmux session
  shell: "{{ item }}"
  with_items:
    - tmux new-session -d -s "start_tmux_server"
    - tmux kill-server
    - tmux new-session -d -s "evilginx2"
    - tmux send-keys -t evilginx2.0 start_evilginx2 ENTER